email:
  subject: "No replay - Cine Force"
  message: "Default Message"

mercado-pago:
  token: ${MP_TOKEN}
  notification-url: http://localhost:8090/api/notification

spring:
  application:
    name: cineforce-api

  datasource:
    url: jdbc:postgresql://localhost:5432/cineforce
    username: postgres
    password: 15032002
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true #ativa autenticação (necessário para Gmail)
      mail.smtp.starttls.enabled: true #habilita TLS
      mail.smtp.starttls.required: true #força TLS, falha se não suportado


  flyway:
    enabled: false   # <- AQUI FUNCIONA