email:
  subject: "No replay - Cine Force"
  message: "Default Message"

mercado-pago:
  token: ${MP_TOKEN}

gcs:
  subdirectory: review
  bucket-name: cineforce-bucket


spring:
  application:
    name: cineforce-api

  datasource:
    url: jdbc:postgresql://localhost:5432/cineforce
    username: postgres
    password: 15032002
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true #ativa autenticação (necessário para Gmail)
      mail.smtp.starttls.enabled: true #habilita TLS
      mail.smtp.starttls.required: true #força TLS, falha se não suportado

  cloud:
    gcp:
      project-id: cineforce
      credentials:
        location: classpath:credentials.json

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB


  flyway:
    enabled: false   # <- AQUI FUNCIONA