spring:
  application:
    name: cineforce-api

  datasource:
    url: jdbc:postgresql://localhost:5432/cineforce
    username: postgres
    password: 15032002
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    enabled: false   # <- AQUI FUNCIONA